package com.example.jatingera.raje

import android.content.Intent
import android.support.v7.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import android.widget.Toast
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseUser
import com.google.firebase.database.DatabaseReference
import com.google.firebase.database.FirebaseDatabase
import kotlinx.android.synthetic.main.activity_main7.*

class Main7Activity : AppCompatActivity() {
    lateinit var firebaseAuth: FirebaseAuth
    lateinit var firebaseUser: FirebaseUser
    lateinit var firebaseDatabase: FirebaseDatabase
    lateinit var databaseReference: DatabaseReference
var n=0;
var uidd= ("abc");
    var i=0;
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main7)
        firebaseAuth=FirebaseAuth.getInstance()
        firebaseDatabase= FirebaseDatabase.getInstance()
        databaseReference=firebaseDatabase.getReference("userdata")

        register1.setOnClickListener{
            var name=name.text.toString()   //cant be blank
            var pass=password1.text.toString()   //min 6 characters
            var ema=email1.text.toString()     //must contain@ and .com  //these comments are needed to be tested by us, fire base throws an exception if any of the above is not satisfied.
            var cont=contactsss.text.toString()     //must contain@ and .com  //these comments are needed to be tested by us, fire base throws an exception if any of the above is not satisfied.
            firebaseAuth.createUserWithEmailAndPassword(ema,pass)
                    .addOnCompleteListener {task->
                        if(task.isSuccessful){
                            Toast.makeText(this,"Account created", Toast.LENGTH_LONG).show()
                             //databaseReference.child("name").setValue(name)
                            // databaseReference.push().child("name").setValue(name)//push is used so that for each new user a new unique key is created.//using child is optional.// but in this method it is difficult to read the key generated by push
                            firebaseUser= firebaseAuth.currentUser!!
                            databaseReference.child(firebaseUser.uid).child("name").setValue(name)
                            databaseReference.child(firebaseUser.uid).child("email").setValue(ema)
                            databaseReference.child(firebaseUser.uid).child("cont").setValue(cont)
                            uidd=firebaseUser.uid
                            var inte=Intent(this,Main8Activity::class.java)
                            inte.putExtra("uidd",uidd)
                            startActivity(inte)
                        }
                        else{
                            Log.w("MainActivity","Exception",task.exception)
                            Toast.makeText(this,"Authentication failed.", Toast.LENGTH_LONG).show()
                        }

                    }
        }


        }
    }

